version: "3"
services:
    bot:
        build: .
        command: npm start
        env_file: .env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
    database:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
        tty: false
volumes:
    mongodb:
