name: Build Test
on:
    push:
        branches:
            - production
            - beta
jobs:
    Test-Docker-Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build the stack
              run: docker-compose up -d --env-file=/dev/null
